// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYNg512-JECr6fyvJeG_6ZTsm18SFfpU',
    appId: '1:966343131611:web:2819460969a546ea9b67fe',
    messagingSenderId: '966343131611',
    projectId: 'movie-ticket-book-69e34',
    authDomain: 'movie-ticket-book-69e34.firebaseapp.com',
    storageBucket: 'movie-ticket-book-69e34.appspot.com',
    measurementId: 'G-Y7VTWJB4H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADhhKV_CRTW-_aanGSOKjg7yrz6xKsK7M',
    appId: '1:966343131611:android:8929cac780a399519b67fe',
    messagingSenderId: '966343131611',
    projectId: 'movie-ticket-book-69e34',
    storageBucket: 'movie-ticket-book-69e34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMO9FkcOydnJO5o734A8P3139q5QO7L3s',
    appId: '1:966343131611:ios:1297e0cbdfb9cac99b67fe',
    messagingSenderId: '966343131611',
    projectId: 'movie-ticket-book-69e34',
    storageBucket: 'movie-ticket-book-69e34.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
